


//---API key generated by open weather map.
const APIKey = "8ef05f7cbf5c643b35bd7aeae8048157";
//---Variables
    const cityInput = document.getElementById("cityInput");
    const searchBtn = document.getElementById("searchBtn");
    const clearBtn = document.getElementById("clearBtn");
    const city = document.getElementById("city");
    const icon = document.getElementById("icon");
    const temperature = document.getElementById("temperature");
    const humidity = document.getElementById("humidity");4
    const wind = document.getElementById("windSpeed");
    const uvIndex = document.getElementById("uvIndex");
    const history = document.getElementById("history");
    let searchHistory = JSON.parse(localStorage.getItem("search")) || [];
    console.log(searchHistory);
    
//---Event listener for search button.
    searchBtn.addEventListener("click",function() {
      const searchTerm = cityInput.value;
      displayWeather(searchTerm);
      searchHistory.push(searchTerm);
      localStorage.setItem("search",JSON.stringify(searchHistory));
      displaySearchHistory();
  })
//---Event listener for clear button
  clearBtn.addEventListener("click",function() {
      searchHistory = [];
      displaySearchHistory();
  })
//--Function for displaying the search history.
  function displaySearchHistory() {
      history.innerHTML = "";
      for (let i=0; i<searchHistory.length; i++) {
//---Creating an input inside the history form and make it read only.
          const cityHistory = document.createElement("input");
          cityHistory.setAttribute("type","text");
          cityHistory.setAttribute("readonly",true);
          cityHistory.setAttribute("class", "form-control d-block bg-white");
          cityHistory.setAttribute("value", searchHistory[i]);
//---Event listener for when a history item is clicked, it will display the weather for that city.
          cityHistory.addEventListener("click",function() {
              displayWeather(cityHistory.value);
          })
          history.append(cityHistory);
      }
  }
//---Display search history from storage    
    displaySearchHistory();
    if (searchHistory.length > 0) {
        displayWeather(searchHistory[searchHistory.length - 1]);
    }

